### ISSUE TITLE
Something wrong with init Gradle setup?

### ISSUE THREAD

**Issue by BartVanRaemdonck** [serenity-bdd/serenity-cucumber4-starter#12]
When I pull this project from scratch, follow the adjustments for Cucumber4, update the chrome driver and then run `gradle clean test` all the test fail.

Im using Gradle version 5.6

Output from commandline:

```
    TEST FAILED WITH ERROR: Refining a search using two terms
    ---------------------------------------------------------------------
    16:33:43.959 [Test worker] ERROR n.t.c.steps.ConsoleLoggingListener - TEST FAILED AT STEP Search for term Cucumber
    16:33:43.960 [Test worker] ERROR n.t.c.steps.ConsoleLoggingListener - element not interactable
    Feature: Research things on the web

      Scenario: Researching a thing                               # src/test/resources/features/research/research_things_on_the_web.feature:3
        Given Sergey is on the DuckDuckGo home page               # SearchOnDuckDuckGoStepDefinitions.i_am_on_the_DuckDuckGo_home_page()
        When he searches for "Duck"                               # SearchOnDuckDuckGoStepDefinitions.i_search_for(String)
          org.openqa.selenium.ElementNotInteractableException: element not interactable
      (Session info: headless chrome=76.0.3809.100)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'BEC02V74Z2HTD5', ip: '10.3.49.217', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.100, chrome: {chromedriverVersion: 76.0.3809.126 (d80a294506b4..., userDataDir: /var/folders/vl/s19rz73j1tx...}, goog:chromeOptions: {debuggerAddress: localhost:64147}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
    Session ID: 153586d9bbd8c00fbd35bcff373caf8a
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
        at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
        at net.serenitybdd.core.pages.WebElementFacadeImpl.clear(WebElementFacadeImpl.java:1257)
        at starter.search.SearchFor.term(SearchFor.java:10)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.CGLIB$term$0(<generated>)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42$$FastClassByCGLIB$$e60e10c4.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
        at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
        at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
        at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
        at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
        at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.term(<generated>)
        at starter.stepdefinitions.SearchOnDuckDuckGoStepDefinitions.i_search_for(SearchOnDuckDuckGoStepDefinitions.java:35)
        at ✽.he searches for "Duck"(src/test/resources/features/research/research_things_on_the_web.feature:5)
    
        Then all the result titles should contain the word "Duck" # SearchOnDuckDuckGoStepDefinitions.all_the_result_titles_should_contain_the_word(String)

      @manual
      Scenario: Researching a thing by hand                           # src/test/resources/features/research/research_things_on_the_web.feature:9
        Given Sergey is on the DuckDuckGo home page                   # SearchOnDuckDuckGoStepDefinitions.i_am_on_the_DuckDuckGo_home_page()
        And he has searched for "Cucumber"                            # SearchOnDuckDuckGoStepDefinitions.i_search_for(String)
        When he searches for "zucchini"                               # SearchOnDuckDuckGoStepDefinitions.i_search_for(String)
        Then all the result titles should contain the word "zucchini" # SearchOnDuckDuckGoStepDefinitions.all_the_result_titles_should_contain_the_word(String)

    Feature: Search by keyword

      Scenario: Searching for a term                                  # src/test/resources/features/search/search_by_keyword.feature:3
        Given Sergey is on the DuckDuckGo home page                   # SearchOnDuckDuckGoStepDefinitions.i_am_on_the_DuckDuckGo_home_page()
        When he searches for "Cucumber"                               # SearchOnDuckDuckGoStepDefinitions.i_search_for(String)
          org.openqa.selenium.ElementNotInteractableException: element not interactable
      (Session info: headless chrome=76.0.3809.100)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'BEC02V74Z2HTD5', ip: '10.3.49.217', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.100, chrome: {chromedriverVersion: 76.0.3809.126 (d80a294506b4..., userDataDir: /var/folders/vl/s19rz73j1tx...}, goog:chromeOptions: {debuggerAddress: localhost:64183}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
    Session ID: 9332c77ecbf6c4ffa63e328227808266
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
        at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
        at net.serenitybdd.core.pages.WebElementFacadeImpl.clear(WebElementFacadeImpl.java:1257)
        at starter.search.SearchFor.term(SearchFor.java:10)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.CGLIB$term$0(<generated>)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42$$FastClassByCGLIB$$e60e10c4.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
        at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
        at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
        at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
        at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
        at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.term(<generated>)
        at starter.stepdefinitions.SearchOnDuckDuckGoStepDefinitions.i_search_for(SearchOnDuckDuckGoStepDefinitions.java:35)
        at ✽.he searches for "Cucumber"(src/test/resources/features/search/search_by_keyword.feature:5)
    
        Then all the result titles should contain the word "Cucumber" # SearchOnDuckDuckGoStepDefinitions.all_the_result_titles_should_contain_the_word(String)

      Scenario: Refining a search using two terms                     # src/test/resources/features/search/search_by_keyword.feature:8
        Given Sergey is on the DuckDuckGo home page                   # SearchOnDuckDuckGoStepDefinitions.i_am_on_the_DuckDuckGo_home_page()
        And he has searched for "Cucumber"                            # SearchOnDuckDuckGoStepDefinitions.i_search_for(String)
          org.openqa.selenium.ElementNotInteractableException: element not interactable
      (Session info: headless chrome=76.0.3809.100)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'BEC02V74Z2HTD5', ip: '10.3.49.217', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.100, chrome: {chromedriverVersion: 76.0.3809.126 (d80a294506b4..., userDataDir: /var/folders/vl/s19rz73j1tx...}, goog:chromeOptions: {debuggerAddress: localhost:64213}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
    Session ID: 3018452c82de4f22ae34d4570cb0497e
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
        at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
        at net.serenitybdd.core.pages.WebElementFacadeImpl.clear(WebElementFacadeImpl.java:1257)
        at starter.search.SearchFor.term(SearchFor.java:10)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.CGLIB$term$0(<generated>)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42$$FastClassByCGLIB$$e60e10c4.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
        at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
        at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
        at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
        at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
        at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.term(<generated>)
        at starter.stepdefinitions.SearchOnDuckDuckGoStepDefinitions.i_search_for(SearchOnDuckDuckGoStepDefinitions.java:35)
        at ✽.he has searched for "Cucumber"(src/test/resources/features/search/search_by_keyword.feature:10)
    
        When he searches for "zucchini"                               # SearchOnDuckDuckGoStepDefinitions.i_search_for(String)
        Then all the result titles should contain the word "zucchini" # SearchOnDuckDuckGoStepDefinitions.all_the_result_titles_should_contain_the_word(String)

    Failed scenarios:
    src/test/resources/features/research/research_things_on_the_web.feature:3 # Researching a thing
    src/test/resources/features/search/search_by_keyword.feature:3 # Searching for a term
    src/test/resources/features/search/search_by_keyword.feature:8 # Refining a search using two terms

    4 Scenarios (3 failed, 1 passed)
    14 Steps (3 failed, 4 skipped, 7 passed)
    0m13,846s

    org.openqa.selenium.ElementNotInteractableException: element not interactable
      (Session info: headless chrome=76.0.3809.100)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'BEC02V74Z2HTD5', ip: '10.3.49.217', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.100, chrome: {chromedriverVersion: 76.0.3809.126 (d80a294506b4..., userDataDir: /var/folders/vl/s19rz73j1tx...}, goog:chromeOptions: {debuggerAddress: localhost:64147}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
    Session ID: 153586d9bbd8c00fbd35bcff373caf8a
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
        at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
        at net.serenitybdd.core.pages.WebElementFacadeImpl.clear(WebElementFacadeImpl.java:1257)
        at starter.search.SearchFor.term(SearchFor.java:10)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.CGLIB$term$0(<generated>)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42$$FastClassByCGLIB$$e60e10c4.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
        at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
        at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
        at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
        at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
        at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.term(<generated>)
        at starter.stepdefinitions.SearchOnDuckDuckGoStepDefinitions.i_search_for(SearchOnDuckDuckGoStepDefinitions.java:35)
        at ✽.he searches for "Duck"(src/test/resources/features/research/research_things_on_the_web.feature:5)

    org.openqa.selenium.ElementNotInteractableException: element not interactable
      (Session info: headless chrome=76.0.3809.100)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'BEC02V74Z2HTD5', ip: '10.3.49.217', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.100, chrome: {chromedriverVersion: 76.0.3809.126 (d80a294506b4..., userDataDir: /var/folders/vl/s19rz73j1tx...}, goog:chromeOptions: {debuggerAddress: localhost:64183}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
    Session ID: 9332c77ecbf6c4ffa63e328227808266
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
        at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
        at net.serenitybdd.core.pages.WebElementFacadeImpl.clear(WebElementFacadeImpl.java:1257)
        at starter.search.SearchFor.term(SearchFor.java:10)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.CGLIB$term$0(<generated>)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42$$FastClassByCGLIB$$e60e10c4.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
        at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
        at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
        at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
        at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
        at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.term(<generated>)
        at starter.stepdefinitions.SearchOnDuckDuckGoStepDefinitions.i_search_for(SearchOnDuckDuckGoStepDefinitions.java:35)
        at ✽.he searches for "Cucumber"(src/test/resources/features/search/search_by_keyword.feature:5)

    org.openqa.selenium.ElementNotInteractableException: element not interactable
      (Session info: headless chrome=76.0.3809.100)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'BEC02V74Z2HTD5', ip: '10.3.49.217', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.100, chrome: {chromedriverVersion: 76.0.3809.126 (d80a294506b4..., userDataDir: /var/folders/vl/s19rz73j1tx...}, goog:chromeOptions: {debuggerAddress: localhost:64213}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
    Session ID: 3018452c82de4f22ae34d4570cb0497e
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
        at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
        at net.serenitybdd.core.pages.WebElementFacadeImpl.clear(WebElementFacadeImpl.java:1257)
        at starter.search.SearchFor.term(SearchFor.java:10)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.CGLIB$term$0(<generated>)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42$$FastClassByCGLIB$$e60e10c4.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
        at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
        at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
        at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
        at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
        at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
        at starter.search.SearchFor$$EnhancerByCGLIB$$a324f42.term(<generated>)
        at starter.stepdefinitions.SearchOnDuckDuckGoStepDefinitions.i_search_for(SearchOnDuckDuckGoStepDefinitions.java:35)
        at ✽.he has searched for "Cucumber"(src/test/resources/features/search/search_by_keyword.feature:10)


4 tests completed, 3 failed
```

**Comment by wakaleo** [comment]
DuckDuckGo UI has changed. Should work now.

**Comment by BartVanRaemdonck** [comment]
Yes it works! Thank you.
