### ISSUE TITLE
[Question] java.lang.NoClassDefFoundError: Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver

### ISSUE THREAD

**Issue by Yiao** [serenity-bdd/serenity-cucumber4-starter#3]
I use serenity-bdd with cucumber4 to generate the cucumber report and I can't run it ... maybe is a problem of version, I didn't found any solution with google ...

I add my errors messages :
```
java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)

java.lang.NoClassDefFoundError: Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver

	at net.thucydides.core.configuration.WebDriverConfiguration.lookupSupportedDriverTypeFor(WebDriverConfiguration.java:45)
	at net.thucydides.core.configuration.WebDriverConfiguration.getDriverType(WebDriverConfiguration.java:33)
```

And my maven file :

```
	<properties>
		<cucumber.version>4.2.0</cucumber.version>
                <serenity.version>2.0.41</serenity.version>
                <serenity.cucumber.version>1.0.6</serenity.cucumber.version>
	</properties>

       <dependencies>
                <dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
                </dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>
                 <dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay-webdriver</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber4</artifactId>
			<version>${serenity.cucumber.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

        <build>
		<plugins>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<configuration>
					<tags>${tags}</tags>
				</configuration>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```

**Comment by Yiao** [comment]
Maybe I must add maven-failsafe-plugin ?

**Comment by sangeethkumarasp** [comment]
I am too getting same exception
[ERROR] initializationError(starter.CucumberTestSuite)  Time elapsed: 0.01 s  <<< ERROR!
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: net/serenitybdd/core/exceptions/SerenityManagedException
Caused by: java.lang.NoClassDefFoundError: net/serenitybdd/core/exceptions/SerenityManagedException
Caused by: java.lang.ClassNotFoundException: net.serenitybdd.core.exceptions.SerenityManagedException

Is it resolved?

**Comment by wakaleo** [comment]
This project is deprecated, use serenity-cucumber-starter instead
