### ISSUE TITLE
Cucumber Feature file Run Issues

### ISSUE THREAD

**Issue by log2jiten24** [serenity-bdd/serenity-cucumber4-starter#30]
While running the Cucumber Feature file I am getting the below error . My feature file is correct and there is no error . Could anyone please help .

Mar 27, 2020 10:13:51 PM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main
Exception in thread "main" cucumber.runtime.CucumberException: Failed to parse resource at: file:/F:/Cucumber_Workspace/SerenityCucumber4/serenity-cucumber4-starter/src/test/resources/features/search/Login_HRM_Application.feature
	at cucumber.runtime.model.FeatureParser.parseResource(FeatureParser.java:40)
	at cucumber.runtime.model.FeatureBuilder.parse(FeatureBuilder.java:25)
	at cucumber.runtime.model.FeatureLoader.loadFromFeaturePath(FeatureLoader.java:36)
	at cucumber.runtime.model.FeatureLoader.load(FeatureLoader.java:23)
	at cucumber.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:33)
	at cucumber.runtime.Runtime.run(Runtime.java:78)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at cucumber.api.cli.Main.run(Main.java:28)
	at cucumber.api.cli.Main.main(Main.java:15)
Caused by: gherkin.ParserException$CompositeParserException: Parser errors:
(1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Author: Kumar Jitendra'
	at gherkin.Parser.parse(Parser.java:143)
	at gherkin.Parser.parse(Parser.java:118)
	at gherkin.Parser.parse(Parser.java:114)
	at cucumber.runtime.model.FeatureParser.parseResource(FeatureParser.java:36)
	... 8 more

**Comment by wakaleo** [comment]
You have a syntax error in your feature file:

Gherkin.ParserException$CompositeParserException: Parser errors:
(1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Author: Kumar Jitendra'

**Comment by ghost** [comment]
Issue is not fixed , pls help me
